### ISSUE TITLE
This should be updated to use jquery

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/jquery-dom-diagnostic#37]

**Comment by payne-chris-r** [comment]
Not sure exactly what you mean here. Do you mean give them an example site (i.e. the Broncos wikipedia) and ask them how to grab specific elements/use $ methods/find what's returned? Looks to me like we're already asking them to write jQ functions... @jrhorn424

**Comment by jrhorn424** [comment]
This was probably old. I can't tell you what I meant, and it looks fine at this point.
