### ISSUE TITLE
DOM tree might need some adjusting

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/jquery-dom-diagnostic#94]
Do we really want a Form inside of the OL? I would expect the h1, form, and ol to come off of 'body', not the way it's currently represented...

**Comment by J-Weeks** [comment]
Gee golly, updated in commit d225cea @payne-chris-r

**Comment by RealWeeks** [comment]
Golly Gee @payne-chris-r fixed in commit d225cea.  Okay to close?  ![bitmoji](https://render.bitstrips.com/v2/cpanel/8149231-136432832_1-s4-v1.png?transparent=1&width=246)

**Comment by payne-chris-r** [comment]
Yuuup. Thanks J.

**Comment by RealWeeks** [comment]
haha, it looks like a little person now.
